export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST = 'FETCH_LIST';
export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_ACTIVE_TAB = 'FETCH_ACTIVE_TAB';
